version: "3.8"

services:
  app:
    image: 'url-shortener:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    environment:
      DOMAIN_NAME: 'http://MyDocker.com'
